### ISSUE TITLE
Facing issue when try to run this Python multiscanner.py <filename>

### ISSUE THREAD

**Issue by kjaisinghyadav** [mitre/multiscanner#146]
Hi,
     I am facing this issue when i try to execute this 
python multiscanner.py "/home/ml/Desktop/All_Exe/pxBinaryViewerSetup_xcsadds.exe"
/usr/lib/libyara.so: undefined symbol: lookup_rule
/multiscanner/modules/Signature/YaraScan.py  not a valid module...
officemeta Could not parse file as an office document

I am using Ubuntu 16.04 and i installed all requirements from "requirement.txt" file.

**Comment by Drewsif** [comment]
It looks like you might have the wrong version of Yara installed. Did you use the install script to install yara or did you use another method?

**Comment by kjaisinghyadav** [comment]
i used script only to install.

**Comment by awest1339** [comment]
Are you able to run yara itself from the cmd line? (http://yara.readthedocs.io/en/v3.7.0/gettingstarted.html#running-yara-for-the-first-time).

Additionally, are you able to run ```$ python -c 'import yara'``` without any errors?

**Comment by kjaisinghyadav** [comment]
yes, i am able to run yara from cmd line and i am running this in ubuntu.
when i am running this  $  python -c 'import yara'  i am getting this error 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python2.7/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python2.7/dist-packages/yara/libyara_wrapper.py", line 362, in <module>
    libyaradll.lookup_rule.restype = POINTER(RULE)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libyara.so: undefined symbol: lookup_rule

**Comment by crypticspawn** [comment]
I also have this issue.  When I run nm -Ca on libyara.so, there is no reference to lookup_rule in it.

Does anyone know which version has this reference?

**Comment by 4thel00z** [comment]
you need to :

1. pip install yara
2. inspect the site packages where the libyara.so lies
3. use strace to determine where it tries to do the dlopen
4. symlink the earlier found libyara.so to that path
